### PR TITLE
feat(backend)

### PR DESCRIPTION
**Pull request by aradhyamathur**
- an integrated backend for site
- added team map as part of site

### CODE REVIEW

**Comment by cereallarceny** [comment]
This potentially could work temporarily, however we're not doing to be using Django for a backend system in the future.  We'll be running Node on the server-side with React on the front-end.  I love the effort that went into this, but it may need to be deemed a temporary solution.

**Comment by aradhyamathur** [comment]
ohk i see

**Comment by iamtrask** [comment]
Indeed, especially since it's a static website

**Comment by iamtrask** [comment]
Very grateful for your work @aradhyamathur . If you're interested, we could chat about some next steps in Capsule :)

**Pull request closed without merging**
